# Generated by Django 3.2.3 on 2021-05-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='entrada',
            fields=[
                ('cod', models.AutoField(primary_key=True, serialize=False)),
                ('numeronf', models.IntegerField()),
                ('dataemissao', models.DateField()),
                ('dataentrada', models.DateField()),
                ('codfornecedor', models.IntegerField()),
            ],
        ),
    ]
